apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zeiterfassung-ingress
  namespace: zeiterfassung
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: zeiterfassung.minikube.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zeiterfassung
                port:
                  number: 8081
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq-ingress
  namespace: zeiterfassung
spec:
  ingressClassName: nginx
  rules:
    - host: rabbitmq.minikube.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rabbitmq
                port:
                  number: 15672
