{{- if .Values.zeiterfassung.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zeiterfassung-ingress
  labels:
    {{- include "zeiterfassung.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.zeiterfassung.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zeiterfassung
                port:
                  number: {{ .Values.zeiterfassung.service.port }}
{{- end }}
