apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    {{- include "zeiterfassung.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "rabbitmq.selectorLabels" . | nindent 4 }}
  ports:
    - name: amqp
      port: {{ .Values.rabbitmq.service.amqpPort }}
      targetPort: {{ .Values.rabbitmq.service.amqpPort }}
    - name: management
      port: {{ .Values.rabbitmq.service.managementPort }}
      targetPort: {{ .Values.rabbitmq.service.managementPort }}
